#!/usr/bin/env python3

import argparse

from pyndeks import Pyndeks

parser = argparse.ArgumentParser(description='Index generator.')
parser.add_argument('topdir',
                    help='Top directory to index.')
parser.add_argument('--ignore',
                    default=None,
                    help='File containing ignored files.')
parser.add_argument('--baseurl',
                    default='',
                    help='Base URL for links.')
args = parser.parse_args()

index = Pyndeks(ignore=args.ignore, baseurl=args.baseurl, topdir=args.topdir)
index.render_all()
